### ISSUE TITLE
Unnecessary preference reversion on shutdown

### ISSUE THREAD

**Issue by Standard8** [mozilla/tp-pref-rollback#2]
There's no need to revert the default preference value on shutdown - Firefox is shutting down, and it won't affect anything, except for taking slightly longer to shutdown.

**Comment by fmarier** [comment]
I added this code to properly clean up the pref should we decide to uninstall the add-on (e.g. if there's a problem with it or we are told to halt the rollback) without restarting Firefox.

I can take it out if you think it's better not to incur the extra shutdown time though.

**Comment by Standard8** [comment]
Ah, if it was uninstall, then doing it in the uninstall() function would have been better. It won't be a significant shutdown hit, but generally better for the long run if we avoid unnecessary shutdown items.
