### ISSUE TITLE
Wiki changes

### ISSUE THREAD

**Issue by ghost** [mozilla/tp-pref-rollback#3]
FYI: The following changes were made to this repository's wiki:

- defacing spam has been removed

- Restricting write access to contributors is strongly encouraged.  Please [make that change](https://github.com/mozilla/tp-pref-rollback/settings)  ([documentation](https://help.github.com/articles/changing-access-permissions-for-wikis/)).

These were made as the result of a recent automated defacement of publically writeable wikis.

**Comment by fmarier** [comment]
@moz-hwine You could also archive (or delete) this whole repo. It was meant only for Fx 57 and we didn't end up using it anyways. It's not needed anymore.

**Comment by ghost** [comment]
I'll archive it.
